language: node_js
node_js:
- 7.7.1
after_script:
- scp -o StrictHostKeyChecking=no app.js root@www.zhoubo.xin:/home/www/yidengtest
before_install:
- openssl aes-256-cbc -K $encrypted_204d80cb93e1_key -iv $encrypted_204d80cb93e1_iv
  -in .travis/id_rsa.enc -out id_rsa -d
- mv id_rsa ~/.ssh -f
- chmod 600 ~/.ssh/id_rsa
# 配置 ssh
- eval $(ssh-agent)
- ssh-add ~/.ssh/id_rsa
- cp .travis/ssh_config ~/.ssh/config
